### ISSUE TITLE
Evaluate rpmlint results at obs

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#114]
Many of the warnings and "errors" the automatic rpmlint run at obs displays are indicating minor flaws and negligences.
While some of these notices are simply wrong, erroneous or misleading and none is preventing Patchmanager from being built and run, most are worth being evaluated and considered.

See "rpmlint results" at https://build.sailfishos.org/package/show/home:b100dian:patchmanager/patchmanager
For convenience / reference the results for Patchmanager 3.1.0 are attached here:
* [rpmlint-results_pm3.1.0_armv7hl.txt](https://github.com/sailfishos-patches/patchmanager/files/7446843/rpmlint-results_pm3.1.0_armv7hl.txt)
* [rpmlint-results_pm3.1.0_aarch64.txt](https://github.com/sailfishos-patches/patchmanager/files/7446844/rpmlint-results_pm3.1.0_aarch64.txt)

**Comment by nephros** [comment]
Some of these I try to address in https://github.com/nephros/patchmanager/tree/rpmlint

**Comment by nephros** [comment]
So I have played around with several variants of rpmlintrc, and it seems impossible to silence most of the silly complaints on OBS.  
ALL packages there get these though (e.g. "weird" permissions for sources).

So I'll pick a couple of trivial things from my tests which actually improve things, but for most cases, these lining results can be ignored.

**Comment by Olf0** [comment]
> So I have played around with several variants of rpmlintrc, and it seems impossible to silence most of the silly complaints on OBS.

That is fine, it is `rpmlint`! :wink: 

> ALL packages there get these though (e.g. "weird" permissions for sources).

It is overly picky and sometimes just wrong.

> So I'll pick a couple of trivial things from my tests which actually improve things, but for most cases, these lining results must be ignored and can not be switched off.

Exactly: Take the complaints by rpmlint as hints and filter the ones, which "actually improve things".
