### ISSUE TITLE
[Usability issue] The detailed Patch information page does not display the version and source of an installed Patch 

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#13]
The detailed Patch information page (reachable by a tap on a Patch name in the top level list of installed Patches) does not display the version and source (from Patchmanager's web catalog or from a RPM) of an installed Patch. 

Tested with Patchmanager 2.3.1-10.39.1.jolla on a Jolla 1 phone under SFOS 2.1.0.11

Originally reported [on TMO as issue 4.](http://talk.maemo.org/showpost.php?p=1527185&postcount=2208) (due to issue #9; filing this here [as promised](http://talk.maemo.org/showpost.php?p=1529055&postcount=2245)).

**Comment by Olf0** [comment]
The detailed Patch information page has been vastly improved with Patchmanager 3.
Thanks!

As of Patchmanager 3.0.51, it now displays the version of Patches installed from Patchmanager's web-catalog, but not for RPM Patches.
It would be nice to also see the version of RPM Patches there, if there are no significant technical hurdles for Patchmanager to obtain the version string of RPM Patches.

**Comment by CODeRUS** [comment]
Check with test version if works correct:
http://repo.merproject.org/obs/home:/coderus:/pm3/sailfish/armv7hl/patchmanager-3.0.53-1.121.1.armv7hl.rpm

**Comment by Olf0** [comment]
Thanks for the new test version, which also shows the "Version" entry in the detailed Patch information page for RPM Patches, but unfortunately it displays "0.0.0" for all installed RPM Patches (no matter if they have been installed before or after the installation of Patchmanager 3.0.53).

And special thanks for fixing the automatic unapplying of RPM Patches in PM3, when they are uninstalled (or updated).

**Comment by Olf0** [comment]
Displaying *0.0.0.0* as version number for all RPM Patches is fixed in Patchmanager 3.0.54, it now displays the whole package name without its extension *.rpm*.  Thanks!

Side note: I originally considered suggesting to filter the version number proper of RPM Patches per RegEx and was about to construct one, but ...
* although most RPM Patches follow a consistent package naming scheme, Patch authors have the freedom to deviate from it.
* it is quite useful to be able to obtain the original package name next to the display name of a RPM Patch.
* that allows for discriminating RPM Patches from web-catalog Patches by the format of their version string displayed in the Patch details (i.e., implicitly and only to the ones being aware of this).
I still believe it would be helpful to explicitly denote the origin of a Patch, e.g. by appending "(web-catalog)" to the version string in the details of Patches from the web-catalog (that is the minimalistic change I can think of to achieve this).
