### ISSUE TITLE
[Bug] Bug when applying multiple Patches in a row

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#14]
**Short description:**
When applying multiple Patches one after the other, freshly enabled Patches are displayed as unapplied after a little while. 

**Steps to reproduce:** 

**a.** Install multiple new Patches (tested with 3 to 6). It does not matter, if from the Web catalog or via RPM (e.g. Warehouse). 

**b.** Enable them one right after the other. Timing does not matter. 

**c.** For each Patch, the cycle is:
- When hitting the button, it lights up (O.K.)
- A notification about installing this Patch is displayed (O.K.).
- After applying the next Patch and waiting for a little while, the button is unlit, again (not O.K.).
So finally it looks like only the last one of the freshly installed Patches is actually applied. 

**d.** Exiting Patchmanager 2.0 and entering it again then correctly shows, which Patches are applied (and which are not). 

**Expected behaviour:**
Buttons indicating an applied Patch stay lit, after applying multiple Patches in a row.

*Edit:* This seems the happen on every multiple "apply" / "unapply" actions in a row: After a while all toggled Patches are displayed as unapplied. Two toggle operations seem to be sufficient to trigger this bug (one of them an "apply" action), and when waiting long enough (not very long), it seems that even the last applied Patch becomes unlit.
This behaviour of Patchmanager 2 made me accidentally reappling an already applied Patch at least twice, but doing so does not seem to cause any harm.

*Edit 2:* Now I observed this happening even after applying just a *single* Patch: Waiting a few seconds, the freshly lit button becomes unlit again. 

Tested with Patchmanager 2.3.1-10.39.1.jolla on a Jolla 1 phone under SFOS 2.1.0.11

Originally reported [on TMO as issue 5.](http://talk.maemo.org/showpost.php?p=1527989&postcount=2224) (due to issue #9; filing this here [as promised](http://talk.maemo.org/showpost.php?p=1529055&postcount=2245)).

**Comment by CODeRUS** [comment]
Please verify in http://repo.merproject.org/obs/home:/coderus:/sailfish/sailfish/armv7hl/patchmanager-2.4.0-10.42.1.jolla.armv7hl.rpm

**Comment by Olf0** [comment]
First of all: Thanks for taking care about the issues filed here.

Certainly I was eager to test:

- Installation went well via `pkcon install-local patchmanager-2.4.0-10.42.1.jolla.armv7hl.rpm` under SailfishOS 2.1.1.26
- But entering Patchmanager fails to list the installed Patches, see attached screenshot: Apparently Patchmanager 2.4.0 hangs in a "busy loop".
- Entering Patchmanager2's Web Catalog works, everything is looks in order there.  But when returning from the Web Catalog page to Patchmanager's main page, it hangs in the same "busy loop", again.
- Entering Patchmanager's "About" page and returning to the main page yields the same result (i.e. "busy loop").

So unfortunately, I cannot test this or any of the other fixes you commited yesterday.

P.S.: I looked at your recent commits and tried to understand Patchmanager's QML code (as sometimes QML is even readable for me as a former Unix administrator and hence mediocre Shell progammer), but failed as Patchmanager consists of too many large pieces of QML (for me) to understand easily, how they interact.

**Comment by Olf0** [comment]
Retested with Patchmanager 3.0.36 (beta) under SFOS 2.2.0 on a Xperia X: Works well.
Thanks!
