### ISSUE TITLE
in many QML files objects named "errorMesageComponent." are referenced.

### ISSUE THREAD

**Issue by b100dian** [sailfishos-patches/patchmanager#141]
in many QML files objects named "errorMesageComponent." are referenced.
Obviously the spelling of "Mesage" is incorrect.  I just wondered, if this is irrelevant, because they are consistently misspelled, or if it this is more than just a name and may not work as intended.
In any case it might be worth to correct all of them (e.g. programmatically by sed etc.), even if it is just a name, because one may spell it correctly when writing new code, which would be wrong and not working as intended.

_Originally posted by @Olf0 in https://github.com/sailfishos-patches/patchmanager/discussions/122_

**Comment by nephros** [comment]
Quoting myself from the other locatin:

> Nice catch, and it's actually just two locations to fix.
> 
> I have a branch dealing with logging and verbosity in the works which now contains the correction for this and will make it into master eventually.

https://github.com/nephros/patchmanager/commits/unverbose
