### ISSUE TITLE
[Usability issue] Minor usability bug, when returning from detailed Patch information page to list view of installed Patches

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#15]
**Observation:**
The specific position of the list view of installed Patches (when returning from a detailed Patch information page) depends on the position of the Patch within the list: 
1. A position above the word "Homescreen" (indicating the start of this section) or one below it with the word "Homescreen" still visible on the device screen / above the eighth Patch or one with the eighth Patch visible:
The list position is the same as before entering the detailed Patch information page (O.K.). 
1. A position so far below the word "Homescreen", that the word "Homescreen" is not visible on the device screen / below the eighth Patch without it being visible:
The list position jumps, so that the first Patch in the section "Homescreen" / the eighth Patch is the topmost displayed one (not O.K.).
(Note that this bug occurs regardless of the device orientation {portrait, landscape}.)

**Expected behaviour:**
The list position is always the same as before entering a Patch's detailed info page. 

Tested with Patchmanager 2.3.1-10.39.1.jolla on a Jolla 1 phone under SFOS 2.1.0.11

Originally reported [on TMO as issue 6.](http://talk.maemo.org/showpost.php?p=1527989&postcount=2224) (due to issue #9; filing this here [as promised](http://talk.maemo.org/showpost.php?p=1529055&postcount=2245)).

**Comment by CODeRUS** [comment]
Please verify in http://repo.merproject.org/obs/home:/coderus:/sailfish/sailfish/armv7hl/patchmanager-2.4.0-10.42.1.jolla.armv7hl.rpm

**Comment by Olf0** [comment]
Oops, as for issue #23, I also missed to test this one, when I had Patchmanager-2.4.0-10.42.1 installed for re-evaluating issue #21 in October, and consequently did not reply.
I am planning to retest with Patchmanager 3 in the next couple if weeks (as you branched off in November, i.e. after [commit e88a92d](https://github.com/sailfishos-patches/patchmanager/commit/e88a92da608cf1f8c9d2943b0e07e6ee7cc9ec9f)), after having installed and configured SFOS on Xperia X.

**Comment by Olf0** [comment]
Retested with Patchmanager 3.0.51 under SailfishOS 2.2.0: I cannot reproduce this anymore.

Thanks!
