### ISSUE TITLE
[Feature suggestion] Display conflicting Patches, when a Patch fails to apply

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#16]
Patches conflicting with each other are creating a "conflict hell", which is really hard to resolve manually. E.g. I am currently unable to identify *all* the Patches (out of about 35 installed ones), which conflict with "Ultimate statusbar patch" or "Devicelock faith text". *Edit:* "Force cover size" and "No notification preview" are conflicting with those two Patches!?!
**Idea:**
It would be extremely helpful for users of Patchmanager2 to be notified specifically, which other Patches (and / or which original file) a Patch conflicts with, when applying it fails.
**Thoughts:**
Basically all information needed is already there: Which lines in which files each Patch patches (and which original lines a Patch expects). So if Patches intend to patch the same lines, they conflict. If there is no conflict between Patches, but the expected original lines are not present, something else is wrong (most likely the Patch is not compatible with the installed SailfishOS version).

Tested with Patchmanager 2.3.1-10.39.1.jolla on a Jolla 1 phone under SFOS 2.1.0.11

Originally reported [on TMO as issue 7.](http://talk.maemo.org/showpost.php?p=1527989&postcount=2224) (due to issue #9; filing this here [as promised](http://talk.maemo.org/showpost.php?p=1529055&postcount=2245)).

**Comment by Olf0** [comment]
Retested with Patchmanager 3.0.51 under SailfishOS 2.2.0:
The new *Possible conflicts* section in a Patch specific page of Patchmanager's list of installed Patches nicely shows possibly conflicting Patches.

Although I have not tested this in practice yet (i.e. with Patches, which do conflict), this is a huge step forward.
Thank your so much.

Although AFAIU ausmt is called to drive "fuzzy" patching, hence only listing the Patches which will definitely conflict seems to be impossible, I have to admit that the number of false positives is quite high.
Are all Patches listed there, which patch the same file(s) or only the ones patching the same lines in these files (or is my thinking too simplistic)?

**Comment by CODeRUS** [comment]
Possible conflicts section only check same patched files. So if you fail to apply some patch which is marked as compatible, you can check if some of possible conflicting patches are already applied.

**Comment by Olf0** [comment]
> Possible conflicts section only check same patched files. 

That explains the high number of false positives well.

> So if you fail to apply some patch which is marked as compatible, you can check if some of possible conflicting patches are already applied.

I know that this was the idea and it is really helpful.
I just thought about ways of lowering the number of false positives.

**Comment by Olf0** [comment]
IMO this is good enough in its current state (PM3.0.5x), hence closing.
