### ISSUE TITLE
[Feature suggestion] Indicate updateable Patches in the web catalog after entering it

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#19]
**Issue description:** Currently one has to individually enter the sub-pages of all installed Patches in Patchmanager2's web catalog to look for updates. For RPM-Patches Warehouse handles this. 

**Possible solution:** Indicate all installed Patches, for which an update is available, with some symbol (e.g. a star or a text "Update available") in the web catalog's top level list, after entering it (and hence refreshing the meta-data of all Patches available there). 

Tested with Patchmanager 2.3.1-10.39.1.jolla on a Jolla 1 phone under SFOS 2.1.0.11

Originally reported [on TMO as issue 10.](http://talk.maemo.org/showpost.php?p=1529052&postcount=2243) (due to issue #9; filing this here [as promised](http://talk.maemo.org/showpost.php?p=1529055&postcount=2245)).

**Comment by Olf0** [comment]
Retested with Patchmanager 3.0.51:
An indicator along some text (including which version an installed patch is upgradeable to) is displayed below the entries in the web catalog list.
Upgrading a Patch by tapping on this text seems to work fine (in contrast to PM2, when I had the impression that one should better carry out the sequence "unapply Patch, uninstall Patch, install new version from web catalog, apply Patch" instead of "click on new version in th Patch specific page of the web catalog to upgrade").

This is looking really nice.  Thanks!

Two things confused me, though:
- The indicator looks like a radio button, but is not toggling when hit.  Am I doing or interpreting something wrong?  If it is without technical function on purpose, a different (or no) indicator may be better.

**Comment by CODeRUS** [comment]
This is definetly not a radio button :))

**Comment by Olf0** [comment]
Just noticed the notification, when testing updateable web-catalog Patches thoroughly in Patchmanager 3.0.51: Excellent!

WRT the update indicator in PM's web-catalog:
It really looks like a radio button to me ![screenshot_20180714_001](https://user-images.githubusercontent.com/16547876/42718068-e80eb168-8705-11e8-8357-1dc4a46ad186.png), at least very, very similar to real radio buttons ![screenshot_20180714_002](https://user-images.githubusercontent.com/16547876/42718106-583b7796-8706-11e8-8501-6063b9f496eb.png)

Well, the functionality is working nicely, I am merely suggesting to use an indicator clearly different from a radio button (to avoid confusion about its function) or none at all (let the existing text be the indicator, plus the nice system notification).

**Comment by Olf0** [comment]
Patchmanager 3.0.54 provides a good solution: Tapping on the "radio button" or anywhere on the updateable Patch on tip of the web-catalog list enters the detailed Patch information page of the web-catalog, where one can update the Patch.
Thanks!
