### ISSUE TITLE
[BUG] Unable to start Camera/Email/Browser after OS update to 4.3.0 with patchmanager 3.1.0

### ISSUE THREAD

**Issue by b100dian** [sailfishos-patches/patchmanager#195]
(From @branja6 on Telegram)

**SailfishOS VERSION** (Settings → About product → Build): 4.3.0.12 EA
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): 
<br />**PATCHMANAGER VERSION** (Settings → Patchmanager → [Top pulley] About): 3.1.0

#### BUG DESCRIPTION
Updating from SFOS 4.2.0 to SFOS 4.3.0 then PM 3.1.0 to PM 3.1.1 with the following patches enabled makes Email/Browser/Camera not start anymore.
<img src="https://user-images.githubusercontent.com/71930/140658752-932b4564-eadc-4c53-a568-24148dba59cb.png" width="384"></img>

Unapplying all patches solves this.

#### STEPS TO REPRODUCE
Apply the above three patches on SFOS 4.2.0 with PM 3.1.0
Upgrade to SFOS 4.3.0
Upgrade to PM 3.1.1
Launch Email - 

#### ADDITIONAL INFORMATION
The day of the upgrade PM 3.1.1 was released and updated.

After Unapply all patches and re-applying them - all good

**Comment by Olf0** [comment]
Sounds really strange to me, even more "*After Unapply all patches and re-applying them - all good*".
Camera app not starting is something a couple of people report for SFOS 4.3.0.12 at FSO.
The issue with this issue is: "*all good*" now, no logs, hence nothing to analyse.

**Comment by branja6** [comment]
[patchmanager.log](https://github.com/sailfishos-patches/patchmanager/files/7500311/patchmanager.log)

Here's the log. I hope it helps. If there's anything else you'd like me to do, just give me a shout on Telegram.

**Comment by b100dian** [comment]
I think for now we can all see if we can reproduce this after upgrading to 4.3.0 when is out of EA. I haven't had issues with Xperia 10 and 4.3.0 EA, but there are at least two more devices by @Olf0 or @nephros that could encounter the bug.
Of course we can close it in the mean while, since the problem is itself solved for @branja6

**Comment by Olf0** [comment]
> I think for now we can all see if we can reproduce this after upgrading to 4.3.0 when is out of EA. I haven't had issues with Xperia 10 and 4.3.0 EA, but there are at least two more devices by @Olf0 or @nephros that could encounter the bug.

Do not expect my to upgrade soon, even when SFOS 4.3.0 is out of EA..

> Of course we can close it in the mean while, since the problem is itself solved for @branja6

I would rather leave it open for a while (some weeks), because it is easier to find for others who may encounter similar issues.
But "Yes", if no other reports show up, I think we should close it without further ado.

**Comment by nephros** [comment]
@branja6 Can you tell us which version of PM you had installed before 3.1.1?
I seem to remember from your original report on Telegram it was the latest one from Coderus' Openrepos repo, i.e 3.0.65, and not 3.1.0 from our repo?

**Comment by branja6** [comment]
I've used the latest version from your repo on Openrepo because Coderus doesn't update his apps anymore (I don't even have his repos enabled in Storeman).

**Comment by Olf0** [comment]
@branja6, @b100dian, @nephros, any new insights?  Or did this issue re-occur?

If not, I suggest to close this issue.

**Comment by b100dian** [comment]
Let's close this. Feel free to re-open on new info.
