### ISSUE TITLE
[Usability issue] Please move the entry "Unapply all patches" in Patchmanager's top level pulley menu one or two positions further up, i.e. *above* the "About" entry

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#20]
**Background:** I accidentally selected "Unapply all patches" numerous times when trying to enter Patchmanager2's web catalog. 
As entering the web catalog is often needed, the pulley menu entry "Unapply all patches" should be moved further away from the web catalog's entry.
Hence please move the entry "Unapply all patches" in Patchmanager2's top level pulley menu one or two positions further up, i.e. *above* the "About" entry. 

Tested with Patchmanager 2.3.1-10.39.1.jolla on a Jolla 1 phone under SFOS 2.1.0.11

Originally reported [on TMO as issue 11.](http://talk.maemo.org/showpost.php?p=1529100&postcount=2249) (filing this here [as promised](http://talk.maemo.org/showpost.php?p=1529055&postcount=2245)).

**Comment by nephros** [comment]
Well, fat-fingering the Pulley menu is something that happens, almost no matter where the menu options are placed.

As a countermeasure, how about adding a Remorse popup?  
That's the usual way of SFOS dealing with destructive changes, is easy to implement and avoids the [xkcd-1172](https://xkcd.com/1172/) effect that a reordering of the menu would have.

**Comment by Olf0** [comment]
O.K., also an apropiate solution (I assumed reordering to be less intrusive / less work).
