### ISSUE TITLE
[Severe bug] Triggering "Unapply all patches" in Patchmanager2's top level pulley menu merely unapplies the first 10 Patches!

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#21]
**Observation:** Triggering "Unapply all patches" in Patchmanager2's top level pulley menu merely unapplies the first 10 Patches!

NB: Hopefully Patchmanager2's built-in patch "Unapply all patches on Upgrade" behaves differently and really unapplies *all* Patches! (I still had Patchmanager1 installed when upgrading from SFOS 2.0.5.6 to 2.1.0.11, so I have not observed this situation, yet.) *Edit:* See [TMO post 2276 by coderus](http://talk.maemo.org/showpost.php?p=1531296&postcount=2276) for an answer.

Maybe this is related to issue #15 (or vice versa).

NB: To be on the safe side, there is https://openrepos.net/content/schturman/patch-unapply-all-patches-system-update-manually

Tested with Patchmanager 2.3.1-10.39.1.jolla on a Jolla 1 phone under SFOS 2.1.0.11

Originally reported [on TMO as issue 12.](http://talk.maemo.org/showpost.php?p=1529100&postcount=2249) (filing this here [as promised](http://talk.maemo.org/showpost.php?p=1529055&postcount=2245)).

**Comment by CODeRUS** [comment]
Please verify in http://repo.merproject.org/obs/home:/coderus:/sailfish/sailfish/armv7hl/patchmanager-2.4.0-10.42.1.jolla.armv7hl.rpm

**Comment by Olf0** [comment]
Well, this seems to be working now (I had the impression *all* active Patches were unapplied when triggering "Unapply all patches" in the pulley menu, at least many more than ten), although I cannot check at the GUI, due to patchmanager-2.4.0-10.42.1 failing to list the installed Patches (see my comment at issue #14). 

But when I tried to revert to Patchmanager 2.3.3 by uninstalling it in Storeman (and later Warehouse), I see that a severe regression was introduced:

So I tried doing this at the CLI: `patchmanager -u` (I did `patchmanager -u sailfishos-browser-patch-right-handed-close-icon > pm2.4.0-u.txt 2>&1`) always segfaults (i.e. stops with `Segmentation fault`).

Thus I checked this at the GUI and CLI with Patchmanager 2.3.3 (with and without this Patch applied): Working well.

Note that the output of Patchmanager 2.4.0 (before it segfaults) is quite different from what Patchmanager 2.3.3 writes to stderr (all tests ar carried out under SFOS 2.1.1.26):
- Patchmanager 2.4.0 (no Patches applied anymore, due to testing "Unapply all patches" successfully): 
- Patchmanager 2.3.3 (please ignore the fact that there are many Patches still applied; IMHO the interesting fact is, that there is no output at all, besides the listing of applied Patches, in contrast to Patchmanager 2.4.0):

**Comment by Olf0** [comment]
After going back to Patchmanager 2.3.3 with `rpm --oldpackage -U patchmanager-2.3.3-10.41.1.jolla_.armv7hl.rpm`, I can see that indeed all Patches were successfully unapplied: So this works now, but aforementioned, freshly introduced regression is quite bad.

**Comment by CODeRUS** [comment]
can you give me link to that patch please?

**Comment by Olf0** [comment]
(https://openrepos.net/content/markkyboy/patch-right-handed-close-icon-tabs-sailfish-browser), but I have the impression that it is just the first Patch Patchmanager 2.4.0 is trying to unapply (as said, unapplying it with Patchmanager 2.3.3 works fine).

**Comment by Olf0** [comment]
If you want me to do some more debugging, I am absolutely willing to: Just tell me what to do, and I will reinstall the test-version and post the requested output here.

**Comment by Olf0** [comment]
Retested with Patchmanager 3.0.6 (beta) under SFOS 2.2.0 on a Xperia X: Works flawlessly (and quick!).

Thanks!
