### ISSUE TITLE
[sort of solved-installation/dependency issue] Cannot apply any patches

### ISSUE THREAD

**Issue by stupidus89** [sailfishos-patches/patchmanager#24]
I had to reset my Jolla 1 due to a failed downgrade to 2.1.0.11. (find the whole story here: https://together.jolla.com/question/168126/after-reset-and-updating-via-commandline-to-21011-phone-still-wants-to-install-11216/)

I am now back on a working 2.1.0.11 installation. But I cannot apply any patches. There is only a notification saying `Failed to install patch`. I tried with multiple different patches. It does not matter if I installed the patch via openrepos, via the webcatalog, or restored it from a backup of my filesystem.

I found the patchmanager CLI command, but I am not sure how to use it. I tried `patchmanager -a /usr/share/patchmanager/patches/sailfishos-patch-volumecontrol/unified_diff.patch`, but there is no output and nothing is changed.

What could be the problem?

patchmanager version: 2.3.3-10.41.1.jolla

EDIT: I did an strace of the above patchmanager command, and there was one curious line: `read(8, "ERROR: Cannot find /usr/bin/patc"..., 34) = 34`
So, I did a `pkcon install patch`, and after that I could apply patches via the GUI.

I had installed patchmanager via the warehouse app. So, there seems to be a problem with the dependencies.

**Comment by CODeRUS** [comment]
Glad you solved it yourself
