### ISSUE TITLE
[Usability issue] The term "developer mode" is confusing users

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#25]
The term "developer mode" in Patchmanager 2.0's pulley menu has already confused users multiple times, resulting in support requests or users silently giving up to install a Patch from Patchmanager 2.0's web-catalog.

Background:
1. The concept of having authors of Patches in the web-catalog updating the SailfishOS compatibility information of their Patches for each SailfishOS release obviously failed (many just don't do this).
2. The current entries "Enable developer mode" and "Disable developer mode" are expressing to which state this setting will be switched, when selecting these pulley entries.  The current state is not immediately obvious (i.e. "Developer mode: off" and "Developer mode: on" would have been better in this regard).
3. Using the term "developer mode" causes a really confusing overlap to the completely unrelated "Developer mode" in the SailfishOS settings.

Hence please change the entries for the "developer mode" in Patchmanager 2.0's pulley menu to e.g.:
* Check SailfishOS version  (instead of "Enable developer mode")
* Don't check SailfishOS version  (instead of "Disable developer mode")

**Comment by nephros** [comment]
I'd like to keep the term because some conversations out there might refer to it, but have added some descriptive text to make clear what it does.

**Comment by Olf0** [comment]
> I'd like to keep the term because some conversations out there might refer to it, but have added some descriptive text to make clear what it does.

Not really: Andrey usually called it "God mode" in forum conversations (at TJC and TMO).
The crucial point is: *3. Using the term "developer mode" causes a really confusing overlap to the completely unrelated "Developer mode" in the SailfishOS settings.*

Your better explanation is really helpful to make it easier to understand, waht it does.
But the term "Developer mode" will stay confusing in the context of SailfishOS, because Jolla used it earlier and much better known for something different.

**Comment by nephros** [comment]
alright.

So the boring choice would me 'Expert mode' I guess.

Or just call it 'I know what I'm doing' or 'Stop nannying me' or 'Gloves off' option.

**Comment by Olf0** [comment]
Thanks, "Allow incompatible patches" is fine for me.

Although I *personally* liked 'I know what I'm doing'- or 'Stop nannying me'- or 'Gloves off'-option much more, but that is (again) incomprehensible for many.
