### ISSUE TITLE
An other way

### ISSUE THREAD

**Issue by wolneykien** [sailfishos-patches/patchmanager#26]
Hi there. As far as I see, the Patchmanager focuses mostly on the .qml files — that's the main purpose the tool was created, isn't it? (Though, the *main* cause is the Jolla licensing policy — see my comment to [the following question on together.jolla.com](https://together.jolla.com/question/54157/sailfishos-open-source-collaboration-meeting-planning/?answer=93248#post-id-93248)). However, patching the root file system is, obviously, not the most secure way to make modifications. Hopefully, with .qml files (and other resources) another way is possible — the QT libraries can be configured to *override* the system UI resources with user specified ones! For example, making the `/home/nemo/ui/jolla-settings/pages/X.qml`, *if it exists*, to take precedence over `/usr/share/jolla-settings/pages/X.qml`. It's nearly as to modify an include path. What do you think about it?

**Comment by CODeRUS** [comment]
patchmanager3 with preload plugin is wip

new version patch fake rootfs in memory

if you want to test drop me a message to telegram - @icoderus

**Comment by wolneykien** [comment]
Thanks. I would like to see the code first, if that's possible.

**Comment by CODeRUS** [comment]
patchmanager3 branch
