### ISSUE TITLE
Missing dependency @OpenRepos / patchutils vs. patch?

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#28]
On a freshly installed phone, installing Patchmanager3-beta failed in Storeman, because the `patchmanager3_beta` repository does not provide the package `patchutils`.
Adding the `coderus` repository resolves this.

Though this minor inconvenience is not really worth writing a bug report, I noted while analysing this, that the original Jolla repositories (i.e., not from Jolla's `mer-tools` repo) provide the package `patch-2.7 5+git1-1.1.1`.
If this version of the `patch` utility suffices Patchmanager's needs, it may be worth considering to depend on that package (instead of an own copy of `patchutils`).

HTH (if not: sorry for bugging you).

P.S.: As a quick measure it may be worth copying the extant `patchutils-0.3.3-10.1.2` package from the `coderus` repo at OpenRepos to the `patchmanager3_beta` repo.

**Comment by Olf0** [comment]
Oops, Jolla's `patch` package is installed after installing `patchutils` from coderus@OpenRepos.

**Comment by CODeRUS** [comment]
Fixed in some of the recent builds
