### ISSUE TITLE
[Minor usability bug] "Busy icon" displayed endlessly after a fresh install of Patchmanager3-beta

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#29]
Patchmanager 3-beta displays an endlessly circling "busy icon" alongside the text "No patches available", when started the first time (i.e., when no Patch is installed).

Installing a single Patch (or more) resolves this.

Expected behaviour:
Patchmanager just displays an empty list of Patches (as there are none installed) or a static Message "No patches installed" (instead of "... available"), but not an continuously circling "busy icon" (while that may appear briefly).

Tested with Patchmanager 3.0.36 under SFOS 2.2.0

An (older) screenshot to depict this issue: ![screenshot_20171003_001](https://user-images.githubusercontent.com/16547876/31153159-d38b2d42-a89f-11e7-98b9-e700fd30de7d.png)

**Comment by Olf0** [comment]
@coderus, I probably won't go back (i.e. uninstalling all Patches) and retest this.

Please close this issue, if a fix for it was among the many "fix" commits in the last couple of weeks.

Supposedly the new procedure (since Patchmanager 2.0.51) to have all Patches "test"-applied on each boot, until *Settings --> Apply on boot* is switched on, hides this (now old) behaviour, anyway.
BTW, there is a typo in the second line of the boot message: *Appled* --> *Applied* (the "i" is missing).

And I cannot reproduce, how I archived to see *Load engine* (instead of *Unapply all patches*) **once** as second entry in the pulley menu of Patchmanager 3.0.51.
It is not really important, I just would like to understand what it is for and when it does appear (maybe others, too).

**Comment by Olf0** [comment]
[*Load engine*] Looks like that has to be done **once** after installing Patchmanager3 (then the entry in Patchmanager's pulley menu is gone).
Still I have no idea why or in which situation (e.g. after an update of Patchmanager3) this may occur again, as I have not found anything documented WRT the *Load engine* function (but maybe I am just too blind to see), e.g. at [OpenRepos](https://openrepos.net/content/patchmanager3beta/patchmanager-3-beta).

**Comment by CODeRUS** [comment]
iirc i removed busy indicator at all some versions ago

**Comment by Olf0** [comment]
... thus closing, as I trust you / your memory.
Thanks.

I will try to remember retesting this, when installing the next SFOS device.

Still a simple explanation of the "Load engine" function (e.g. on PM3's OpenRepos page) would be nice and helpful.
