### ISSUE TITLE
[Minor observation] Why is the clock symbol shown only for `3.4.0.24_i486` at SailfishOS:Chum testing?

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#292]
Only a minor observation, yet: Why is the clock symbol shown only for the target [`3.4.0.24_i486` at SailfishOS:Chum testing](https://build.sailfishos.org/package/show/sailfishos:chum:testing/patchmanager), in contrast to the same target at [the regular SailfishOS:Chum repository](https://build.sailfishos.org/package/show/sailfishos:chum/patchmanager)?

Hovering with the mouse over the clock symbol displays "No build possible atm, waiting for jobs in other repositories".  But exactly the same symbol and message is shown for the disabled targets, too.

It has been in this state for about 7 hours, and I cannot detect any difference in the configuration of `3.4.0.24_i486` at SailfishOS:Chum testing compared to the other targets there or at the regular SailfishOS:Chum repository (including `3.4.0.24_i486` there).

**Comment by nephros** [comment]
This phenomenon seems to have gone away.

Closing as "mysterious", can be re-opened if it appears again.
