### ISSUE TITLE
[Minor PM3 usability issue] List of Patches is not immediately refreshed, when uninstalling a Patch

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#30]
When uninstalling a Patch (tested with an already unapplied RPM patch) in PM3's list of installed ("Available") Patches, the list is not refreshed immediately.
When trying to reapply the freshly uninstalled Patch (just for fun / testing), PM3 emits a notification "Failed to install patch" and crashes (the whole Settings app).

When reopening Patchmanager, the list entry is still there, but now empty (i.e., no Patch name displayed)  Looking at its Patch details PM3 states, "This patch is no[t] available anymore. You won't be able to reinstall it."  Hopefully I **will** be able to ever reinstall it (after a reboot or so). ;\

And ultimately PM3 does not crash, when trying to enable the "empty Patch" a second or third time: It just (correctly) emits a notification, "Failed to install patch".

Testing environment: PM3.0.51, SFOS2.0.2.29, sbj

**Comment by Olf0** [comment]
Tried again (with a different Patch), now being more patient: The list **is** refreshed after uninstalling a Patch, but it takes about 10 seconds to happen (on a Jolla 1 phone).

And no harm done at all: After rebooting the empty entry (created by impatiently applying a freshly uninstalled Patch) in PM3's list of installed Patches is gone. :)

O.K., definitely not a bug, just a minor usability issue for impatient people.

**Comment by CODeRUS** [comment]
It would be cool if you can attach logfile with reproduced issues to your reports, with timings when bug was reproduced 😀

**Comment by Olf0** [comment]
Sure, using the instructions (*journalctl* options) [from OpenRepos](https://openrepos.net/content/patchmanager3beta/patchmanager-3-beta): [patchmanager3.0.51_olf-jolla1a.log](https://github.com/sailfishos-patches/patchmanager/files/2181809/patchmanager3.0.51_olf-jolla1a.log)

But after the long preamble of loading Patches (loading them automatically on boot was off), there is not much to see IMHO (and setting the environment variables NO_PM_PRELOAD / PM_PRELOAD_DEBUG makes no sense, as preloading is off and this does not seem to be related to it).

I booted, waited a while, started Patchmanager, unapplied *Ultimate statusbar patch* and finally uninstalled *Ultimate statusbar patch* in Patchmanager 3.0.51.  It took 20 seconds (on a stopwatch) for the entry to vanish after the remorse timer for uninstalling it timed out.  Then I left Patchmanager, closed the Settings app and captured a log per *journalctl -al _COMM=jolla-settings + _EXE=/usr/sbin/patchmanager + _EXE=/usr/bin/patchmanager-dialog > patchmanager.log*.

**Comment by Olf0** [comment]
Well, I considered closing this "issue" as too insignificant meanwhile:
Even though impatient people may create an "empty Patch" entry in PM3, it seemed that handle that well, and after a reboot everything seems to be in order.

So if you have ideas how to easily ...
* reduce the time between the end of the remorse timer and the visual deletion of a Patch, when uninstalling it in PM3
* or immediately inhibit applying a Patch, when uninstalling it in PM3

... it may be worth trying.  Otherwise, just leave it as it is and close this "issue".

**Comment by Olf0** [comment]
BTW (if that is relevant): *Ultimate statusbar patch* (the one uninstalled for testing) was the last (i.e. bottom-most) in PM3's list of the many Patches installed.

**Comment by CODeRUS** [comment]
Please reproduce with this version and send me new log. This may help to find bottleneck.
http://repo.merproject.org/obs/home:/coderus:/pm3/sailfish/armv7hl/patchmanager-3.0.53-1.121.1.armv7hl.rpm

**Comment by Olf0** [comment]
Well, with v3.0.53 RPM Patches are not uninstalled anymore, when using the context menu function "Uninstall" in Patchmanager's main window.  Checked with pkcon and Storeman, that the Patches are still installed after triggering an uninstall action in Patchmanager.  Patchmanager's debug output in the journal (see below) states the opposite: "Removing ... Success"!?!
Note, Patches from the web-catalog still can be uninstalled this way.

Nevertheless I took a log (using a different example this time, I also tried others), which nicely shows the uninstall action at 00:24:10: [patchmanager3.0.53_olf-jolla1a.log](https://github.com/sailfishos-patches/patchmanager/files/2216585/patchmanager3.0.53_olf-jolla1a.log)

**Comment by CODeRUS** [comment]
Thanks. THis one should be fixed in http://repo.merproject.org/obs/home:/coderus:/pm3/sailfish/armv7hl/patchmanager-3.0.54-1.122.1.armv7hl.rpm

**Comment by Olf0** [comment]
ACK, uninstalling RPM Patches works again in Patchmanager 3.0.54.
Will capture a fresh log.

Behaviour is unchanged yet, i.e. it still takes 20 seconds for the list entry of the uninstalled Patch to vanish (on a Jolla 1 phone) and *Apply* is still accessible in the context menu during that time.

**Comment by CODeRUS** [comment]
Behaviour is unchanged. I only need a fresh log with current version to debug issue.

**Comment by Olf0** [comment]
Fresh log taken with Patchmanager 3.0.54: [patchmanager3.0.54_olf-jolla1a.log](https://github.com/sailfishos-patches/patchmanager/files/2236722/patchmanager3.0.54_olf-jolla1a.log)

Uninstall action started 19:32:22 (picked a different RPM Patch, again) and rhis time I exited Patchmanager (and subsequently the Settings app) right after the Patch entry vanished in Patchmanager's list of installed Patches (19:32:46).

**Comment by CODeRUS** [comment]
good, thanks, i'll take a look what i can do.

**Comment by CODeRUS** [comment]
3.0.55 is coming with fix for this bug.

**Comment by CODeRUS** [comment]
http://repo.merproject.org/obs/home:/coderus:/pm3/sailfish/armv7hl/patchmanager-3.0.55-1.123.1.armv7hl.rpm
