### ISSUE TITLE
Can not be installed on 4.4.0.58EA

### ISSUE THREAD

**Issue by nephros** [sailfishos-patches/patchmanager#301]
**SailfishOS VERSION** (Settings → About product → Build): 4.4.0.58 (EA)
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): unknown
<br />**PATCHMANAGER VERSION** (Settings → Patchmanager → [Top pulley] About): unknown

#### BUG DESCRIPTION

Leszek reported in the Telegram channel that:

1. the 4.4 update process removes patchmanager (which AFAIK is a first)
2. it can not be installed after the update because of missing dependencies

#### ADDITIONAL INFORMATION

Which dependencies are failing to resolve is currently unknown.

**Comment by nephros** [comment]
The current version (3.2.2) has the following dependencies on SFOS 4.3 according to OBS:

```
config(patchmanager) = 3.2....	patchmanager
grep	gnu-grep busybox-symlinks-grep
ld-linux-armhf.so.3	glibc
ld-linux-armhf.so.3(GLIBC_2.4)	glibc
libQt5Core.so.5	qt5-qtcore
libQt5Core.so.5(Qt_5)	qt5-qtcore
libQt5DBus.so.5	qt5-qtdbus
libQt5DBus.so.5(Qt_5)	qt5-qtdbus
libQt5Gui.so.5	qt5-qtgui
libQt5Gui.so.5(Qt_5)	qt5-qtgui
libQt5Network.so.5	qt5-qtnetwork
libQt5Network.so.5(Qt_5)	qt5-qtnetwork
libQt5Qml.so.5	qt5-qtdeclarative
libQt5Qml.so.5(Qt_5)	qt5-qtdeclarative
libQt5Quick.so.5	qt5-qtdeclarative-qtquick
libQt5Quick.so.5(Qt_5)	qt5-qtdeclarative-qtquick
libc.so.6	glibc
libc.so.6(GLIBC_2.28)	glibc
libc.so.6(GLIBC_2.4)	glibc
libc.so.6(GLIBC_2.9)	glibc
libdl.so.2	glibc
libdl.so.2(GLIBC_2.4)	glibc
libgcc_s.so.1	libgcc
libgcc_s.so.1(GCC_3.5)	libgcc
libnemonotifications-qt5.so.1	nemo-qml-plugin-notifications-qt5
libpthread.so.0	glibc
libpthread.so.0(GLIBC_2.4)	glibc
librpm.so.9	rpm
libsailfishapp.so.1	libsailfishapp
libstdc++.so.6	libstdc++
libstdc++.so.6(CXXABI_1.3)	libstdc++
libstdc++.so.6(CXXABI_1.3.9)	libstdc++
libstdc++.so.6(CXXABI_ARM_1...	libstdc++
libstdc++.so.6(GLIBCXX_3.4)	libstdc++
libstdc++.so.6(GLIBCXX_3.4.11)	libstdc++
libstdc++.so.6(GLIBCXX_3.4.9)	libstdc++
libsystemd.so.0	systemd-libs
libsystemd.so.0(LIBSYSTEMD_...	systemd-libs
patch	patch
qml(Nemo.Configuration)	nemo-qml-plugin-configuration-qt5
sailfish-version >= 3.4.0	sailfish-version
sed	gnu-sed busybox-symlinks-sed
unzip	unzip
```

**Comment by nephros** [comment]
The 4.4 change log is here: https://forum.sailfishos.org/uploads/short-url/cpTMCkPDCSDMNj7QgNLUMQbE59.md

**Comment by nephros** [comment]
It seems the new RPM library is a likely culprit. I have tried to build a version linked against a zstd-enabled rpmlib [here](https://build.sailfishos.org/project/show/home:nephros:devel:patchmanager) but can't test on 4.4

**Comment by a-dekker** [comment]
FYI: I gave the new rpm a try on my Xperia XA2, seems to work fine on my 4.4 install. Thanks!

**Comment by b100dian** [comment]
@nephros with 3.2.2 downloaded from github I get 
```
# zypper in --oldpackage Downloads/patchmanager-3.2.2-1.armv7hl.rpm
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'librpm.so.8' needed by the to be installed patchmanager-3.2.2-1.armv7hl
 Solution 1: do not install patchmanager-3.2.2-1.armv7hl
 Solution 2: break patchmanager-3.2.2-1.armv7hl by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c):
```
(I already have the OBS/chum one downloaded and running successfully)

Which means that the build from our github CI is using an older SDK I believe.

**Comment by nephros** [comment]
Thanks.

Another user reported success with the regular 4.3 chum version on 4.4.

So maybe this bug isn't actually a bug.

BTW, librpm.so.8 is in 4.2, I believe 4.3 has .so.9

**Comment by Olf0** [comment]
> FYI: I gave the new rpm a try on my Xperia XA2, seems to work fine on my 4.4 install. Thanks!

@a-dekker, does the Patchmanager 3.2.2 release built for SFOS 4.3.0.15 from SailfishOS:Chum not install and run fine on SFOS 4.4.0?  I believe it should.

Please install via SailfishOS:Chum GUI app or manually from https://build.sailfishos.org/package/show/sailfishos:chum/patchmanager

**Comment by Olf0** [comment]
> BTW, librpm.so.8 is in 4.2, [I believe 4.3 has .so.9](https://github.com/sailfishos-patches/patchmanager/issues/301#issuecomment-1073010490)

That must be the case, because

> [(I already have the OBS/chum one downloaded and running successfully)](https://github.com/sailfishos-patches/patchmanager/issues/301#issuecomment-1073002706)

> Which means that the build from our github CI is using an older SDK I believe.

Yes, deliberately 4.0.1, see #303.

**Comment by Olf0** [comment]
What remains open is 
> … the real question is how to handle that at Openrepos. I currently cannot think of any way out, besides either stating there, "Use SailfishOS:Chum for SFOS ≥ 4.4.0.", or "Use SailfishOS:Chum for SFOS < 4.3.0." BTW, first I have to get Storeman working properly on SFOS 4.4.0, any way.

My current plan is to add a comment "Use SailfishOS:Chum for SFOS < 4.3.0." at OpenRepos, plus delete all Patchmanager RPMs there and only add the current one for SFOS 4.3.0.15, when I have Storeman working properly on SFOS 4.4.0.

@b100dian & @a-dekker, can you please briefly test, if [the Storeman Installer built for SFOS 4.3.0.15](https://build.sailfishos.org/package/show/sailfishos:chum:testing/harbour-storeman-installer) works when started at the GUI (i.e., from the "launcher") on SFOS 4.4.0?  You do not need to uninstall Storeman for this test (if you do not plan do install the downloaded RPM).  (I assume I have to bail out of SailJail, but would not, if it is unnecessary.)

P.S.: I added [a note for the 3.2.2 release here at GitHub](https://github.com/sailfishos-patches/patchmanager/releases/tag/3.2.2).

**Comment by a-dekker** [comment]
@Olf0 although your last question is not related to this subject: the Storeman installer was not successful for me a few days ago, so I installed harbour-storeman-0.2.12-1 directly. And I had to disable SailJail afterwards to make it work in my case.

**Comment by Olf0** [comment]
> @Olf0 although your last question is not related to this subject:

Yes, this is only loosely related.

> the Storeman installer was not successful for me a few days ago,

- Due to SailJail (i.e., Storeman Installer works when started from the command line)?
- Already on SFOS 4.4.0.x?

> so I installed harbour-storeman-0.2.12-1 directly. And I had to disable SailJail afterwards to make it work in my case.

[I know that](https://github.com/storeman-developers/harbour-storeman/pull/235).
But not for Storeman Installer, unfortunately, and …
> > (I assume I have to bail out of SailJail for Storeman Installer, too, but would not, if it is unnecessary.)

**Comment by Olf0** [comment]
I suggest to close this.  Opinions?

**Comment by nephros** [comment]
closing, please reopen if there are any problems in 4.4 proper

**Comment by Olf0** [comment]
> My current plan is to add a comment "Use SailfishOS:Chum for SFOS < 4.3.0." at OpenRepos, plus delete all Patchmanager RPMs there and only add the current one for SFOS 4.3.0.15, when I have Storeman working properly on SFOS 4.4.0.

Done.
