### ISSUE TITLE
[BUG] After updating to 4.4.0 getting lib preload error even after uninstalling Patchmanager

### ISSUE THREAD

**Issue by JacekJagosz** [sailfishos-patches/patchmanager#304]
**SailfishOS VERSION** (Settings → About product → Build): 4.4.0
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Sony Xperia 10
<br />**PATCHMANAGER VERSION** (Settings → Patchmanager → [Top pulley] About): 3.2.2

#### BUG DESCRIPTION
Each time I enter the terminal or execute a command I get `ERROR: ld.so: object '/usr/lib/libpreloadpatchmanager.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.` printed many times.
This keeps happening even after I uninstalled Patchmanager.

#### STEPS TO REPRODUCE
Had newest Patchmanager on 4.3.0 with option to apply patches at boot enabled.
Installed 4.4.0 through GUI.

#### ADDITIONAL INFORMATION

(Please consider which other pieces of information may be relevant, e.g. denote if this is not always reproducible, if it is a regression, attach relevant data such as log files or the systemd journal, provide screenshots etc.)

**Comment by JacekJagosz** [comment]
Ok, I managed to fix it by removing `/usr/lib/libpreloadpatchmanager.so` from `/etc/ld.so.preload`

**Comment by Olf0** [comment]
@JacekJagosz, thank you for your comprehensive report.  While the fact that Patchmanager currently fails on SailfishOS 4.4.0 is not nice at all, your bug report really is.  Thank you!

We are trying to analyse the issue.

For the sub-issue why this message persists after removing ("uninstalling") Patchmanager, I have to admit I am confused, because [`libpreloadpatchmanager.so` should be unregistered form `/etc/ld.so.preload` by the `%postun` section of Patchmanager's spec file](https://github.com/sailfishos-patches/patchmanager/blob/master/rpm/patchmanager.spec#L196).

Hence my question: How did you remove Patchmanager and did that work flawlessly (i.e., without any errors or warnings)?

**Comment by nephros** [comment]
Note that `/var/log/zypp/history` should contain output from the %post macro, so if there is something interesting there please share it.

**Comment by JacekJagosz** [comment]
I am very confused. After update to 4.4.0 the Patchmanager seemed broken. When I entered its page in settings I only got a spinning wheel, which was the only result I could get. Not patch was applied either. I also was getting those terminal error I mentioned. I uninstalled it using `pkcon`, don't know if that makes a difference, but `/var/log/zypp/history` tell me nothing:
```
# 2022-03-21 22:47:13 patchmanager-2.3.3-10.41.1.jolla.armv7hl removed ok
# Additional rpm output:
# ERROR: ld.so: object '/usr/lib/libpreloadpatchmanager.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ig
nored.
# ERROR: ld.so: object '/usr/lib/libpreloadpatchmanager.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ig
nored.
# Uninstalling package
# ERROR: ld.so: object '/usr/lib/libpreloadpatchmanager.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ig
nored.
# ERROR: ld.so: object '/usr/lib/libpreloadpatchmanager.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ig
nored.
# ERROR: ld.so: object '/usr/lib/libpreloadpatchmanager.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
# Uninstalling package
# ERROR: ld.so: object '/usr/lib/libpreloadpatchmanager.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
# ERROR: ld.so: object '/usr/lib/libpreloadpatchmanager.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
# 
2022-03
```
The weirdest thing is that patchmanager does work on 4.4.0. After a suggestion of @lolek on forum.sailfishos.org I installed it manually from chum and it does work flawlessly, not even terminal errors. So that is good news, you probably don't need to patch anything for 4.4.0. Just weird it didn't survive the update. Maybe it was just on my phone and will be fine for others?

**Comment by Olf0** [comment]
There it is again, a reference to Patchmanager 2.3.3 (in then first line of the log you quoted)!  According to the lolek's post at FSO I quoted above, it became installed during the upgrade from SFOS 4.3.0 to 4.4.0.  `patchmanager-2.3.3-10.41.1.jolla.armv7hl` is the last Patchmanager 2 version and [Coderus still offers it at his Pachmanager 3.0 page at OpenRepos](https://openrepos.net/content/coderus/patchmanager-30) (and hence in his RPM repository there). 

I assume you still have the `coderus` repository at OpenRepos enabled.  Please check via `ssu lr | fgrep coderus` if that outputs a line containing `openrepos-coderus`.  If it does I suggest that you disable it via `ssu dr openrepos-coderus`.

Please report your results here, most importantly if you still had the `coderus` repository at OpenRepos enabled.

**Comment by Olf0** [comment]
BTW, user s_mario at FSO also [reports that Patchmanager 3.2.2 compiled for SFOS 4.3.0 is installing and working fine on SFOS 4.4.0](https://forum.sailfishos.org/t/release-notes-vanha-rauma-4-4-0/10656/194).

**Comment by nephros** [comment]
> There it is again, a reference to Patchmanager 2.3.3 (in the first line of the part of the log you quoted)! According to the lolek's post at FSO I quoted above, it became installed during the upgrade from SFOS 4.3.0 to 4.4.0. `patchmanager-2.3.3-10.41.1.jolla` is the last Patchmanager 2 version and [Coderus still offers it at his Pachmanager 3.0 page at OpenRepos](https://openrepos.net/content/coderus/patchmanager-30) (and hence in his RPM repository there).
> 
> I assume you still have the `coderus` repository at OpenRepos enabled. Please check via `ssu lr | fgrep coderus` if that outputs a line containing `openrepos-coderus`. If it does, I suggest that you disable it via `ssu dr openrepos-coderus`.
> 
> Please report your results here, most importantly if you still had the `coderus` repository at OpenRepos enabled.

I think this warrants a section in the Release Notes. Users should disable the `coderus` repo before upgrading if this can actually make the update fail.
There's little we can do about that.

**Comment by JacekJagosz** [comment]
> There it is again, a reference to Patchmanager 2.3.3 (in the first line of the part of the log you quoted)! According to the lolek's post at FSO I quoted above, it became installed during the upgrade from SFOS 4.3.0 to 4.4.0. `patchmanager-2.3.3-10.41.1.jolla` is the last Patchmanager 2 version and [Coderus still offers it at his Pachmanager 3.0 page at OpenRepos](https://openrepos.net/content/coderus/patchmanager-30) (and hence in his RPM repository there).
> 
> I assume you still have the `coderus` repository at OpenRepos enabled. Please check via `ssu lr | fgrep coderus` if that outputs a line containing `openrepos-coderus`. If it does, I suggest that you disable it via `ssu dr openrepos-coderus`.
> 
> Please report your results here, most importantly if you still had the `coderus` repository at OpenRepos enabled.

YUP. I had this enabled! Thank you, hope others can now have smooth experience when upgrading!

**Comment by Olf0** [comment]
> Ok, I managed to fix it by removing `/usr/lib/libpreloadpatchmanager.so` from `/etc/ld.so.preload`

Installing a current release of Patchmanager (> 3.1.0) also fixes this, [see `s_mario`'s last bullet point here](https://forum.sailfishos.org/t/release-notes-vanha-rauma-4-4-0/10656/194).

**Comment by Olf0** [comment]
#### Summary
Something goes wrong in Jolla's upgrade procedure for SailfishOS 4.4.0: It automatically installs the (historic) `patchmanager-2.3.3-10.41.1.jolla`, when the RPM repository `openrepos-coderus` is enabled.

Note that this is not the newest version of Patchmanager in this repository (but the oldest), so it appears as if something explicitly installs this version of Patchmanager.  Which does sound very strange indeed, but no SailfishOS upgrade before this one exhibited this behaviour.

**Comment by nephros** [comment]
Maybe this ancient version of PM does not have a dependency on librpm and hence is the one decided on by pkcon/zypper as the only installable version?

**Comment by JacekJagosz** [comment]
@nephros I think that is exactly what happened. Just after the update I uninstalled and was trying to install Patchmanager it, complained about lacking librpm.

**Comment by Olf0** [comment]
> Maybe this ancient version of PM does not have a dependency on librpm and hence is the one decided on by pkcon/zypper as the only installable version?

Well, that is a build-dependency on `rpm`.   But "Yes", it was introduced with PM 3.0, see [spec-file of PM 3.0](https://github.com/sailfishos-patches/patchmanager/blob/3.0.65-2/rpm/patchmanager.spec#L36) versus [spec-file of PM 2.0](https://github.com/sailfishos-patches/patchmanager/blob/patchmanager2/rpm/patchmanager.spec#L17).

Does that translate into a run-time dependency, which can be checked with `rpm -qR patchmanager`?  I still fail to fully comprehend what is happening.

**Comment by nephros** [comment]
rpmbuild adds runtime deps to the package dynamically, so even if there is no Requires: in the spec, if a binary in the package links against libfoo.so it will Require libfoo.so.

I think one can see those requirements  using `rpm -qR`, yes.

**Comment by Olf0** [comment]
> A `pkcon install`or `pkcon update --allow-downgrade` will then select that old version if the coderus repo is enabled, ~unless there is a 4.3 chum repo active as well~. I would expect that configuration to be typical for a freshly upgraded device by a long-time user (so using PM, therefore has coderus repo enabled, plus hopefully the patchmanger repo and maybe chum). _Also_, because of the `vendor` field that chum sets, even an enabled chum repo will _not_ be considered a valid upgrade path unless the currently installed patchmanager was already from chum and not from openrepos.

That is the point I missed.  Thanks!

> If that is so, one solution would be to put a special 4.3-compiled version (from Github CI, or OBS, but NOT Chum) on Openrepos, so updaters find a compatible version.

GitHub CI does not work for that AFAIU.
As this should be done before SFOS 4.4.0 goes GA, I [used OBS for that](https://build.sailfishos.org/package/show/home:olf:patchmanager/patchmanager) and uploaded [these RPMs to OpenRepos](https://openrepos.net/content/patchmanager/patchmanager).  Vendor is now "meego" instead of "chum".

**Comment by nephros** [comment]
Thank you.

I guess that should do it, although I'm not sure vendor change if "unset" -> "meego" or the other way around will work.

**Comment by Olf0** [comment]
> I guess that should do it, although I'm not sure vendor change of "unset" -> "meego" […] will work.

I am sure it does, because …

> > […] For PM 2 & 3.0 all RPMs have the vendor set to "meego", so I assume this should be fine (because PM 2.3.3 was installed on SFOS upgrade to 4.4.0), right?

> or the other way around

… is irrelevant, because that is not the case here.
