### ISSUE TITLE
[Bug?] PM may contribute to user data loss when switching accounts

### ISSUE THREAD

**Issue by nephros** [sailfishos-patches/patchmanager#311]
**SailfishOS VERSION** (Settings → About product → Build): 4.4.0.58 
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): XA2 Dual SIM
<br />**PATCHMANAGER VERSION** (Settings → Patchmanager → [Top pulley] About): 
<br />

#### BUG DESCRIPTION

When using multi-user (2 users), data from one user gets suddenly totally deleted and phone goes to first boot “Ahoj” window, leaving the user’s dir emptyed, excepted the android_storage directory.
This happens when starting (and?/or) stopping Android support and changing user right after.

#### STEPS TO REPRODUCE

See https://forum.sailfishos.org/t/multi-user-android-user-data-get-deleted-and-lost-device-reset/11520

#### ADDITIONAL INFORMATION

While this has not definitely been confirmed, according to the Bug Report analysis, PM may be involved.

**Comment by nephros** [comment]
My hunch is that something in the preloadpatchmanager library might have to do with this, but I'm not sure how.

See e.g. https://github.com/sailfishos-patches/patchmanager/blob/master/src/preload/src/preloadpatchmanager.c#L104

**Comment by nephros** [comment]
[Damien's comment](https://forum.sailfishos.org/t/multi-user-android-user-data-get-deleted-and-lost-device-reset/11520/10) indicates it can happen without us, which is good news in some way.

**Comment by Olf0** [comment]
And this is what the original reporter (ric9k) [ultimately also concludes](https://forum.sailfishos.org/t/multi-user-android-user-data-get-deleted-and-lost-device-reset/11520/14): Shall we close this.

Side note: From my perspective the information provided in [the corresponding FSO thread](https://forum.sailfishos.org/t/multi-user-android-user-data-get-deleted-and-lost-device-reset/11520/) was never substantial enough to open a bug report in the first place; I would have done that, if it was described as definitely reproducible or confirmed by a second user (neither ever happened).

**Comment by nephros** [comment]
Agreed, closing.
