### ISSUE TITLE
[PM3 bug] Fails to uninstall RPM Patches

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#32]
Patchmanager 3.0.55 fails to uninstall RPM Patches per selecting "Uninstall" in the context menu of a Patch in Patchmanager's list view (i.e. its primary window): The remorse timer is triggered, but when it timed out nothing happens.

Tested under SFOS 2.2.0, 2.2.1 and 3.0.0 on a Jolla 1 phone and an Xperia X.
Workaround: Using Storeman, pkcon, zypper or rpm to uninstall an RPM Patch.
P.S.: I could swear (I know, one shouldn't ;) ) to have filed this issue before, but was unable to find it.

**Comment by Olf0** [comment]
I believe I re-tested this with PM 3.0.57 a few months ago and it appeared to be fixed.
But honestly, I do not really remember, thus I am leaving this issue open until someone confirms that this is working again.

**Comment by nephros** [comment]
Closing this, it indeed appears to be working correctly in current versions.
