### ISSUE TITLE
`tar_git` at SFOS-OBS assembles an incorrect changelog

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#327]
**PATCHMANAGER VERSION**: 3.x.y

#### BUG DESCRIPTION

`tar_git` assembles an incorrect changelog, see [e.g. for v3.2.4](https://build.merproject.org/package/view_file/sailfishos:chum:testing/patchmanager/_service:tar_git:patchmanager.changes?expand=1).

Consequently `rpmlint` at the SFOS-OBS complains:
`patchmanager.aarch64: W: incoherent-version-in-changelog 3.2.3 ['3.2.4-1.12.1.jolla', '3.2.4']`
`The latest entry in %changelog contains a version identifier that is not coherent with the epoch:version-release tuple of the package.`

AFAICS, Patchmanager currently does not provide an `rpm/patchmanager.changes` file, a `%changelog` section in the spec file or any other file accumulating the changes for each release.

#### STEPS TO REPRODUCE

Compile Patchmanager 3 at the SailfishOS-OBS.

#### ADDITIONAL INFORMATION

As we provide proper changelogs in [Patchmanager's releases page at GitHub](https://github.com/sailfishos-patches/patchmanager/releases) and git provides full traceability on commit level, IMO `git_tar`'s flaw provides insufficient reason to address this by duplicating administrative work (i.e., maintain two changelogs, which must be kept in sync).

Consequently I labelled this as `#wontfix`.  If someone thinks this is wrong, please remove the `#wontfix` label and address this issue.

**Comment by nephros** [comment]
That rpmlint complaint stems from the Version-Release mangling the OBS build process does.

Even if there were a .changelog file this would appear for every rebuild (the x.y.z-jolla revisions OBS generates).

AFAIK one could use a .changes.in file which can generate a changelog from git, and possibly would shut up rpmlint.

**Comment by Olf0** [comment]
> That rpmlint complaint stems from the Version-Release mangling the OBS build process does.

Yes, see [my analysis of Jolla's `tar_git`](https://github.com/sailfishos-chum/main/issues/77#issuecomment-1079780452).

> Even if there were a .changelog file this would appear for every rebuild (the x.y.z-jolla revisions OBS generates).

Ack. 

> AFAIK one could use a .changes.in file which can generate a changelog from git, and possibly would shut up rpmlint.

IMO a lot of effort and maintenance for minimal, and only potential gain (it may not work this way, too).

Basically I created this issue to document exactly that, plus the consequence: **Won't fix**.
Hence closing this issue now.  Cool, one now can close an issue at GitHub as *"Not planned (Won't fix, can't repro, duplicate, stale)"*!

**Comment by Olf0** [comment]
Oh, actually the measure suggested in PR #395 makes the SFOS-OBS do nothing, plus suppresses the `rpmlint`'s error, see e.g., https://build.merproject.org/package/show/sailfishos:chum:testing/sailfishos-chum-gui-installer

**Comment by Olf0** [comment]
Found more references:
- In [Jolla's Sailfish-SDK documentation, page "Building packages", chapter "Packaging formats, section "tar_git packaging structure"](https://docs.sailfishos.org/Tools/Sailfish_SDK/Building_packages/#tar_git-packaging-structure), second paragraph
- In one of Fedora's many RPM documentation locations: [`rpmautospec`, which provides the `%autorelease` and `%autochangelog` RPM macros](https://fedoraproject.org/wiki/Changes/rpmautospec) appears to be what Jolla's `tar_git` uses

**Comment by Olf0** [comment]
The guess in the second bullet point above was wrong, `tar_git` does not use RPM macros, but does everything on its own:
The [shell script's main section]](https://github.com/MeeGoIntegration/obs-service-tar-git/blob/master/tar_git#L1238) calls [the function `generate_changes`](https://github.com/MeeGoIntegration/obs-service-tar-git/blob/master/tar_git#L533-L627), which does a lot, among calling [the function `do_changelog_block`](https://github.com/MeeGoIntegration/obs-service-tar-git/blob/master/tar_git#L506-L531).
