### ISSUE TITLE
[Bug] Missing translation strings

### ISSUE THREAD

**Issue by eson57** [sailfishos-patches/patchmanager#357]
**SailfishOS VERSION** (Settings → About product → Build): 4.4
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Xperia 10 lll
<br />**PATCHMANAGER VERSION** (Settings → Patchmanager → \<Top pulley\> → About): 3.2.4
<br />

#### BUG DESCRIPTION
There is two untranslated entrys in settings page.

> Show 'Deactivate all Patches' pulley menu entry

and

> Enable an additional pulley menu entry for Patchmanager's main page to deactivate all Patches.

#### STEPS TO REPRODUCE
Open Patchmanager's settings page

#### ADDITIONAL INFORMATION
Missing strings are...

```
    <message>
        <location filename="../src/qml/SettingsPage.qml" line="101"/>
        <source>Show &apos;Deactivate all Patches&apos; pulley menu entry</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/qml/SettingsPage.qml" line="102"/>
        <source>Enable an additional pulley menu entry for Patchmanager&apos;s main page to deactivate all Patches.</source>
        <translation type="unfinished"></translation>
    </message>
```

**Comment by Olf0** [comment]
@nephros and @b100dian, I assume this is a simply a matter of another `lupdate` / `lrelease` run, right?

Can either of you please perform that (if this fixes this issue) and push the changes?
