### ISSUE TITLE
Pasword recovery does not work in PM2 web page

### ISSUE THREAD

**Issue by qeef** [sailfishos-patches/patchmanager#38]
I forgot the password to https://coderus.openrepos.net/pm2/ but the password recovery does not work.

Also, it's quite complicated to *Please contact us if you have any trouble resetting your password.* when there is no contact information provided.

**Comment by CODeRUS** [comment]
Thanks for report, probably some problem with mail server.

**Comment by qeef** [comment]
Btw still not working.

**Comment by CODeRUS** [comment]
I had no time to look at the problem, no eta

**Comment by qeef** [comment]
Ok, I will be patient.

**Comment by qeef** [comment]
Is there anything new with this issue? It's stupid, but I can't update my patches to SailfishOS 3.

Thanks.

**Comment by qeef** [comment]
Still relevant.

**Comment by qeef** [comment]
Tested today and it worked.
