### ISSUE TITLE
[Bug] allow incompatible not working as expected

### ISSUE THREAD

**Issue by nephros** [sailfishos-patches/patchmanager#405]
it seems #334 introduces one or several bugs where

1. the setting isn't initialized properly after updating from a previous version of PM. One has to toggle the option list to make the wanted option stick.
2. ~~while incompatible patches are allowed to be activated and show up as such, the aren't actually applied by the PM backend.~~ <-- not actually *this* bug here

test example patches: 
 - "smooth remorse timers"
 - "browser tab pulley menu"

**Comment by Olf0** [comment]
Do I understand correctly, that point 2 is not a regression, i.e., "always has been this way for PM3"?

Does "the setting" in point 1 address only a Patch's "enabled / disabled" status as GUI (= user) setting?

**Comment by Olf0** [comment]
> The interesting part I'm not sure about is:
> If I
>  * LD_PRELOAD=patchmanager.so[version X] lipstick
>  * ... do things
>  * update PM so it installs patchmanager.so[version Y] 
>  * do _not_ restart lipstick
> 
> ... will patchmanager.so[version Y] do its thing? I think not, as it's not really loaded into the lipstick process.

Soi it is basic requirement would be to reload the shared library `patchmanager.so` (in its freshly deployed version Y), which means to restart the daemonized Patchmanager running in the background (correctly understood?): Is this feasible at all?

**Comment by Olf0** [comment]
> About 1, I think what happens is:
> 
> […]
> now at this point (on a never-migrated system), `PatchManager.sfosVersionCheck` is undefined, so it gets set to `VersionCheck.Strict`. So far so good, we agreed that we should default to the conservative option.
> 
> But that I think does _not_ trigger the `onCurrentIndexChanged` signal handler, so the actual PM setting never gets set.
> 
> Only interactively toggling the switch will do it.

Reading this, it sound not hard to resolve, if that is indeed the cause, right?

**Comment by Olf0** [comment]
> […] (At most, we can give a note to the user they should reboot after install but, _meh_.)

Well, this is better than something not working without such a indication ("without a reboot strange things may happen").  Jolla's `version dup` does exactly that (though it is a CLI app).

> BUT, in reality this should rarely be needed as breaking changes to the .so almost never happen.

Mmmh, *you* observe it, so anybody else could.
I will follow any assessment from you here, because I do not have the time and barely have the know-how to retrace that, but just want to ask "checks & balances" questions.

P.S.: I had to chuckle when reading "Incidentially", because I tend to do the same spelling mistake and a related one regularly with a couple of similar words.  But there is no second "i" in "accidentally", "incidentally", plus there is no "c" but (always a) a "t" in these: "instantiated", the aforementioned two and a couple of similar ones.  I love to spell "accidencially" etc. and wonder what's wrong.

**Comment by Olf0** [comment]
> Summing up:
> * wrt. changes to the shared library:
>   IF […]

IMO this is way too complicated to communicate and to remember and check when doing such a "potentially critical" release.  Is there anything wrong in communicating:

Do always reboot after deploying a different Patchmanager release: I.e., after every installation, upgrade, re-installation (or even downgrade) of Patchmanager!

This is simple and unambiguously phrased statement, which is easy to comprehend and unconditionally applicable.
If you agree I will try to find am appropriate location (e.g., the user section of our README) to denote that.

> * wrt. restarting the PM daemon after an update:
>   If I read the .spec correctly, we already do that more than once in the %post/%preun/%postun scriptlets. I think I might hit the special case that I sometimes (from rpm's point ov view) do a downgrade of PM, in which case the argument handling in those scriptlets might decide a reload/restart is not necessary.

I might take a look at this, if we can easily restart more often unconditionally.  Though, I may not be able to perform this task properly without in-depth knowledge what happen outside of the spec file (i.e., in / by Patchmanager).

> * wrt. the actual bug here
>   I'll do some more tests to verify what has been said, but is seems clear to me the upgrade handling should be moved from QML into the daemon, as it may be a long period of time between a PM upgrade and the user going into Settings in the UI.

:+1:

>   Alternatively, migration could be done in the .spec directly on the config file, but that feels a bit hackish to me. OTOH it means less "dead" code in the product itself.

Sounds good (and simpler) to me.  Maybe we should rather follow thus route (plus that will be maintainable by shell code / spec file adaptions only).

> Also, users should be made aware of this bug, and while no definite fix has been deployed, be advised to go into Settings and confirm their preference there (and as [noted](https://github.com/sailfishos-patches/patchmanager/issues/405#issuecomment-1407752344), there may be no other way to resolve it).

> Personally, I shall test more thoroughly in the future :D

Lol, a conclusion most developer regularly come to.  But then, time is scarce, I rather implement new things that to test thoroughly: This is why I love CI runs and do deliberately cut down on testing recently (only "smoke tests": it is O.K. if it starts and performs its basic functionality fine).  Plus it is FLOSS: No formal responsibility, and while I try to not publish crap, to shift testing in detail to users is a valid strategy to rather code than test by oneself.  YMMV, but I do believe it makes sense to evaluate every now and then how much time to spend on which FLOSS activities to be most efficient and effective.

**Comment by b100dian** [comment]
> I'll do a quick post about it on the Forum

Thanks for this and for the investigation.
