### ISSUE TITLE
PM3.0.61 crashes when trying to see the patch info on SFOS 3.2.0

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#43]
Patchmanager 3.0.61 always crashes when trying to enter a Patch's information page on SailfishOS 3.2.0, regardless if that Patch is applied or not.  It even happens when all Patches are unapplied.

"Crashing" means, Lipstick is restarted hard, and then all Patches are unapplied, Patchmanager's engine unloaded (*Load engine* entry in Patchmanager's pulley menu) and Patchmanager is in a special failure mode (*Resolve failure* entry in pulley).
Interestingly, entering and exiting the details page of any Patch works fine in this state.
1. Using *Resolve failure* to resolve this results in returning to the original state: "PM3.0.61 always crashes when trying to enter a Patch's details page."
2. Using *Load engine* to resolve this seems to make PM3.0.61 behave well, until *Resolve failure* is used (which then is still present in the pulley menu, apparently indicating that still something is wrong), ultimately ending up at point 1.

Under usability aspects, it is really annoying that all Patches are unapplied, after this issue has hit.

All this was working fine with Patchmanager 3.0.57 under SailfishOS 3.0.3 on this Xperia X.

As always, feel free to request special logs.

**Comment by CODeRUS** [comment]
using patchmanager-3.0.61-1.135.1?

**Comment by Olf0** [comment]
No, patchmanager-3.0.61-1.134.1

**Comment by CODeRUS** [comment]
anywaay, 3.0.62 should work much better

**Comment by Olf0** [comment]
Yes, it does.
Thank you!
