### ISSUE TITLE
[Bug] Overwrite a old version archive does not work

### ISSUE THREAD

**Issue by robang74** [sailfishos-patches/patchmanager#440]
Current 2.0 web interface for developers: https://coderus.openrepos.net/pm2

#### BUG DESCRIPTION

Trying to overwrite a past version archive file does not work. Everything seems fine but PM2 keeps the old version of the archive. IMHO, it is a feature not a bug - possibly a constrain set pourposely by a specific configuration - in this case, it is a bug because the UI part related to that feature should not even displayed. 

#### STEPS TO REPRODUCE

Try to overwrite the archive of a published version.

#### ADDITIONAL INFORMATION

Chrome browser for Ubuntu.

**Comment by Olf0** [comment]
Thank you for the bug report and using the bug teplat3e for it.

Though this seems to be addressing the UI of the PM2-Webcatatlog, which is hosted here: https://github.com/CODeRUS/django-test
If my interpretation is correct (i.e., this is not directly related to Patchmanager proper), please file the bug report there.

Side note: Mind, that the PM2-Webcatalog software is in minimal maintenance mode.  Contributions (i.e., PRs) are welcome, but must be well tested and positive testing results demonstrated, before a PR may be accepted.

**Comment by robang74** [comment]
Thanks, reported to the right github project. I close this.

**Comment by robang74** [comment]
Thanks, reported to the right github project. I close this.

**Comment by Olf0** [comment]
Sure.
