### ISSUE TITLE
Clicking on a patch with no main.qml should show info page

### ISSUE THREAD

**Issue by b100dian** [sailfishos-patches/patchmanager#54]
As reported https://forum.sailfishos.org/t/patchmanager-patches-in-koli-4-0-1/4925/143

**Comment by nephros** [comment]
Should be fixed in cb01a77.

**Comment by b100dian** [comment]
Closing,
@hsjpekka There's a build[1] in chum:testing if you want to test it out, feel free to re-open this bug if it doesn't work for you. Thanks!

https://build.sailfishos.org/package/show/sailfishos:chum:testing/patchmanager

**Comment by Olf0** [comment]
Is this [altered line in a commit by elros34 for "PM2-forever"](https://github.com/elros34/patchmanager/commit/ac0991b1b27df010066fa4e3f8f287c6b1004a3e#diff-da6a1e0621bec30e25650901e8a69669572d302bbccc7f82e5fc81f4b90e4e68L312) related to this?

Here is [the corresponding line in PM3 for the commit resolving this issue](https://github.com/sailfishos-patches/patchmanager/commit/cb01a770a91fbf4f1c68454e4f6b6e709f6c42f5#diff-da6a1e0621bec30e25650901e8a69669572d302bbccc7f82e5fc81f4b90e4e68L388).

Just wondering, if this change for PM2 is also useful for PM3, but lack the understanding to determine & decide that.

**Comment by nephros** [comment]
> Is this [altered line in a commit by elros34 for "PM2-forever"](https://github.com/elros34/patchmanager/commit/ac0991b1b27df010066fa4e3f8f287c6b1004a3e#diff-da6a1e0621bec30e25650901e8a69669572d302bbccc7f82e5fc81f4b90e4e68L312) related to this?


Yep, seems likely, that is just a very minor cleanup of code duplication that was introduced in cb01a77.

**Comment by Olf0** [comment]
> > Is this [altered line in a commit by elros34 for "PM2-forever"](https://github.com/elros34/patchmanager/commit/ac0991b1b27df010066fa4e3f8f287c6b1004a3e#diff-da6a1e0621bec30e25650901e8a69669572d302bbccc7f82e5fc81f4b90e4e68L312) related to this?
> 
> Yep, seems likely, that is just a very minor cleanup of code duplication that was introduced in [cb01a77](https://github.com/sailfishos-patches/patchmanager/blame/cb01a770a91fbf4f1c68454e4f6b6e709f6c42f5/src/qml/PatchManagerPage.qml#L386)

Thanks for looking this up, when and by whom this line was introduced.

But so I suppose it makes sense to introduce that fix-up also here at PM3, correct?

**Comment by nephros** [comment]
> But so I suppose it makes sense to introduce that cleanup also here at PM3, correct?

I have it in a "trivial fixups" branch - i'll put it in one of my next PRs that seems appropriate.
