### ISSUE TITLE
Is the syntax of lines 50 & 51 in the spec file correct?

### ISSUE THREAD

**Issue by Olf0** [sailfishos-patches/patchmanager#60]
Lines 50 & 51 in the [spec file](https://github.com/sailfishos-patches/patchmanager/blob/master/rpm/patchmanager.spec#L50-L51), which are currently
```
/usr/lib/qt5/bin/qmlplugindump -v -noinstantiate -nonrelocatable org.SfietKonstantin.patchmanager 2.0 %{buildroot}%{_libdir}/qt5/qml > %{buildroot}%{_libdir}/qt5/qml/org/SfietKonstantin/%{name}/plugin.qmltypes |:
sed -i 's#%{buildroot}##g' %{buildroot}%{_libdir}/qt5/qml/org/SfietKonstantin/%{name}/plugin.qmltypes
```
do not make sense to me:
1. In line 51 (the `qmlplugindump` call) 
   * The trailing `|:` must be wrong, because `qmlplugindump`'s output to std-out must be redirected to a file via `>`, so an additional redirection via a pipeline is nonsense, plus the bash built-in `:` does not read anything from std-in.
     Hence I assume it was supposed to be `||:`, which I would write as `|| true`.
   * I was not able to determine from [`qmlplugindump`'s documentation](https://doc-snapshots.qt.io/qtcreator-4.0/creator-qml-modules-with-plugins.html#generating-qmltypes-files), in which cases it may fail (making a `||:` or `|| true` necessary), but it states "*You can safely ignore the debug output.*", which means adding a `2> /dev/null` in order to discard it here (i.e., in a spec file).
   * Additionally I do not comprehend why `qmlplugindump` is called with then `-v` flag, but then its debug output is not used.
     For `qmlplugindump`'s source code and calling conventions, see https://code.woboq.org/qt5/qtdeclarative/tools/qmlplugindump/main.cpp.html#744
   * Furthermore that line is too long IMO, so this flaw at the line's end is not easily noticed.
2. Line 52 is supposed to process the freshly generated file, eliminating the prefix `%{buildroot}` for every path listed in it.
  ~~But I have never seen `sed`'s substitute command to work with the delimiter `#` (instead of `/`), and its man-page also does not list `#` as a special character.
  Am I completely missing some aspect (e.g., something crazy like `rpmbuild` transforms `#` which are not at the start of a line to `/`), or is this simply wrong?~~
  I was [simply wrong](https://github.com/sailfishos-patches/patchmanager/issues/60#issuecomment-926189148).

Thus I posed commit https://github.com/sailfishos-patches/patchmanager/pull/61/commits/036b6e71b29a75fbc889c02a24a2b1fec73a745e per MR #61, rewriting this line to
```
/usr/lib/qt5/bin/qmlplugindump -noinstantiate -nonrelocatable org.SfietKonstantin.patchmanager 2.0 %{buildroot}%{_libdir}/qt5/qml \
> %{buildroot}%{_libdir}/qt5/qml/org/SfietKonstantin/%{name}/plugin.qmltypes 2> /dev/null || true
```
, plus eliminating the `\` at lines [105](https://github.com/sailfishos-patches/patchmanager/blob/master/rpm/patchmanager.spec#L105) and [141](https://github.com/sailfishos-patches/patchmanager/blob/master/rpm/patchmanager.spec#L141), because these lines are not overly long (for today's standards, i.e. up to 132 characters).

@nephros, @b100dian, am I missing something or does that make sense?

P.S.: `qmlplugindump` was [fixed in SailfishOS 3.3.0](https://together.jolla.com/question/222222/changelog-330-rokua/#222222-sailfishsilica-qt5)

**Comment by CODeRUS** [comment]
`|:` is a typo indeed `2>/dev/null` is better option

`/` delimiter can't be used in this commanbd, because `%{buildroot}` contains a path, so safe delimiter `#` was choosen
and yes, sed can use any edlimiter you want, even space: `s %{buildroot}  g` is valid

**Comment by Olf0** [comment]
> `/` delimiter can't be used in this command, because `%{buildroot}` contains a path, so safe delimiter `#` was choosen
> and yes, sed can use any delimiter you want, even space: `s %{buildroot} g` is valid

Thanks, I faintly remembered something like this, but could not find a reference in sed's man-page.
But the first sentence of the fifth paragraph in [this section of sed's info-page](https://www.gnu.org/software/sed/manual/sed.html#The-_0022s_0022-Command) hints that (could be stated clearer though, IMO).

**Comment by nephros** [comment]
> > `/` delimiter can't be used in this command, because `%{buildroot}` contains a path, so safe delimiter `#` was choosen
> > and yes, sed can use any delimiter you want, even space: `s %{buildroot} g` is valid
> 
> Thanks, I faintly remembered something like this, but could not find a reference in sed's man-page.
> But the first sentence of the fifth paragraph in [this section of sed's info-page](https://www.gnu.org/software/sed/manual/sed.html#The-_0022s_0022-Command) hints that (could be stated clearer though, IMO).

The simple rule is: for regex expressions like this, any character after the `s` will be treated as the delimiter for the expression (unless it is a reserved one, which I haven't looked up). That's not a sed thing either, works with almost any regex eating program, perl, awk, vi etc.
