### ISSUE TITLE
[Sandboxing] Review the way things work in the light of full application sandboxing

### ISSUE THREAD

**Issue by nephros** [sailfishos-patches/patchmanager#64]
This is upcoming:

https://blog.jolla.com/whats-up-with-sandboxing/

We should collect how this will affect us in this thread.

Things to look at:

- [ ] calling DBus services we do not ship
- [ ] reading/writing files outside of `/usr/share/patchmanager` (e.g. `/etc`)

Actions to take:

- [ ] create an application profile for patchmanager

**Comment by CODeRUS** [comment]
hope jolla-settings will have enough permissions :)
in worst scenario making separate desktop file for patchmanager :)

**Comment by b100dian** [comment]
Hopefully sandboxing only applies for applications launched with the desktop file - and the Settings plugin should only talk through DBus with patchamanger-daemon, which we ship.., hopefully that's still possible.
Need to have 4.3 to test though.
Then, if Storeman can still install RPMs we should be good (famous last words)

**Comment by CODeRUS** [comment]
sure, and settings for sure will have permissions to talk with dbus :))

**Comment by Olf0** [comment]
See also [point 2 here](https://github.com/sailfishos-patches/patchmanager/pull/65#issuecomment-930535505) for my contribution to this discussion.

Plus mind that Andrey usually "knows & has future" WRT SFOS.

**Comment by b100dian** [comment]
> With the upcoming Sailfish OS 4.3.0, you can also test if your application works with the default profile. You can enable the default profile by adding a file called “50-enable-sandboxing.conf” in /etc/sailjail/config, with the content:
```
[Default Profile]
Enabled=true
```

Just enabled this, all seems good. All apps started to require microphone/bluetooth/camera/internet/location/media index/NFC/play and record audio/removable media/user directories and web contet, but jolla-settings did not.

**Comment by Olf0** [comment]
Oh, IMO this needs some pondering how to proceed procedurally:
As discussed at https://github.com/sailfishos-patches/patchmanager/discussions/113#discussioncomment-1582443 I believe / prefer to "single out" critical changes.  I think switching on the sandboxing this is one, but may be convinced of the opposite.
But if we agree that this may have unforseeable side-effects, I would like to do a 3.1.1 release without sandboxing activated, a 3.1.2 with it and ultimately a 3.2.0 release with the "32 /64 bit mangling" merged.

**Comment by b100dian** [comment]
Sandboxing above was not enabled for patchmanager. We are using the jolla-settings desktop file I believe.
That setting was just the global sandboxing for all apps and in my testing it did not impacted our settings plugin (but it did impact e.g. IRC as pictured above).
So there is no sandboxing we can/should/(must?) enable. We can continue as we are AFAICT

**Comment by Olf0** [comment]
> [...] We are using the jolla-settings desktop file I believe.

Sorry, that was the point I missed.
The rest is a logical consequence of that, then.

**Comment by nephros** [comment]
Closing the issue then, its purpose was served and no actions needed for now.
