### ISSUE TITLE
unapplyAllPatches broke Sailfish OS updates page

### ISSUE THREAD

**Issue by inta** [sailfishos-patches/patchmanager#7]
I installed the latest update of "patchmanager for Jolla settings" and applied the patch "Unapply all patches on Upgrade". After a reboot I am not able to open the Sailfish OS updates page – it just does not respond to taps. I tried removing the unapply all patches patch but that failed.

**Comment by CODeRUS** [comment]
PR pending: https://github.com/sailfishos-patches/patchmanager/pull/6

**Comment by CODeRUS** [comment]
for fixing that menu entry simple do following:
pkcon install jolla-settings-sailfishos
