### ISSUE TITLE
Patches with targets in /usr/lib[,64] do not apply on 32/64bit systems

### ISSUE THREAD

**Issue by nephros** [sailfishos-patches/patchmanager#71]
Systems with 64bit userland use `/usr/lib64` instead of `/usr/lib`as a library path.
Patches which target files in either of those locations will therefore not apply on the other platforms even though the patched files themselves might be the same.

This affects e.g. all "silica" patches, as the Sailfish QML files live under `$LIBDIR/qt5/qml/Sailfish/*`, and basically anything QML that isn't applications in `/usr/share`.

This means patch developers must currently ship and deploy two versions of each patch, and create two projects on web catalog, or use RPM packaging which installs the appropriate patch version.

Question:

Shall patchmanager implement something that helps with this problem?

Solutions that come to mind:

 - use something like `patch -p3 --dry-run -d /usr/lib{,64}/` when a `/usr/lib` string is detected in the patch file
   - probably the simplest and fastest way, but is it reliable?
   - breaks when files outside of `/usr/lib` are patched from the same diff file
 - accept a second diff file in the patch hierarchy (e.g. `unified_diff_64.patch`) so devs can ship either or both
   - this would require modifcation of both patchmanager and the Web Catalog validator for submitting tarfiles
 - modifying Web Catalog to mangle any uploaded diffs to create the missing variant, and supply the correct tarball when PM downloads, so PM always receives a valid patch depending on bittiness
   - wonky, as the catalog can't verify that a file will exist on the system
 - modify `/usr/lib*` paths in existing unified_diff files when installing a patch from Web Catalog 
 - modify `/usr/lib*` paths in existing unified_diff files when applying a patch at runtime 
 - faking the libpath (force /usr/lib also on 64bit) somehow when applying a patch
   - the last three would allow old 32bit patches to be used without the authors needing to update them
 - Other ideas?

**Comment by nephros** [comment]
Whatever solution, it would probably be useful to add a section in the patch.json schema to allow authors to specify whether their patch is for 32 or 64 bit systems, and whether it is expected to work on either.

something like

    "bittiness": "32|64|96"

meaning 32-bit only, 64-bit only, or both.

**Comment by CODeRUS** [comment]
`patch ... < sed "s#/usr/lib#/usr/lib64#g"` instead

**Comment by b100dian** [comment]
There's also the reverse fact - patches written for 64 bits only would fail on 32 bits.

**Comment by CODeRUS** [comment]
add vice versa conversion for 32 bit systems :)

**Comment by b100dian** [comment]
Definitely possible to add the feature to web catalog, I've been playing with this https://github.com/CODeRUS/django-test/compare/master...b100dian:bitness#diff-6bf3ea544666deef7ce7c8cf29e7bfd9956ca032bb933f870dd271782de3f837R141
(work in progress, needs to link the bitness choice to the unified_diff64.patch presence)

**Comment by CODeRUS** [comment]
do you have any examples of difference in files of lib and lib64?

**Comment by b100dian** [comment]
I think it boils down to patches going to `/usr/lib/qt5/qml/` - example https://coderus.openrepos.net/pm2/project/sailfishos-default-allowed-orientations-patch
So the sed fix would work with that, but if you also want to patch other `/usr/lib/`paths, say, `systemd` then the sed command won't work (there's not `/usr/lib64/systemd`.

**Comment by nephros** [comment]
> do you have any examples of difference in files of lib and lib64?

You mean examples of e.g. Sailfish Silica files that are different between 32 and 64 bit versions? I don't have an example of any, but I think it's possible there will be differences. It's probably not safe to assume they are identical, although they will likely be in most cases.

**Comment by Olf0** [comment]
Just for reference: This has been enhanced per PR #221 and #225.
